djangoonlinestore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('category/', include('category.urls')),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

home/urls.py
from django.urls import path

from home.views import HomeTemplateView

urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home')
]

category/models.py
from django.db import models


class Category(models.Model):
    category_name = models.CharField(max_length=30)
    category_description = models.CharField(max_length=300)

    def __str__(self):
        return self.category_name

product/models.py
from django.db import models


class Product(models.Model):
    product_name = models.CharField(max_length=30)
    product_sku = models.CharField(max_length=5)
    product_price = models.IntegerField()
    product_description = models.CharField(max_length=300)
    category = models.ForeignKey('category.Category', on_delete=models.CASCADE, default=None, null=False)

    def __str__(self):
        return self.product_name

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">
    <link rel="stylesheet" href="{% static 'css/my_style.css' %}">
</head>
<body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="https://bulma.io">
         {#  <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28"> #}
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            {% if perms.product.view_product %}
          <a class="navbar-item" href="{% url 'product_list' %}">
            Products List
          </a>
            {% endif %}
            {% if perms.category.view_category %}
          <a class="navbar-item" href="{% url 'category_list' %}">
            Categories
          </a>
            {% endif %}
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              More
            </a>

            <div class="navbar-dropdown">
              <a class="navbar-item">
                About
              </a>
              <a class="navbar-item">
                Jobs
              </a>
              <a class="navbar-item">
                Contact
              </a>
              <hr class="navbar-divider">
              <a class="navbar-item">
                Report an issue
              </a>
            </div>
          </div>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              <a class="button is-primary" href="{% url 'users_create' %}">
                <strong>Sign up</strong>
              </a>
                {% if user.is_authenticated %}
                <a class="button is-light" href="{% url 'logout' %}">
                Log out, {{ request.user.first_name }} {{ request.user.last_name }}
              </a>
                {% else %}
                <a class="button is-light" href="{% url 'login' %}">
                Log in
              </a>
                {% endif %}
            </div>
          </div>
        </div>
      </div>
    </nav>
{% block content %}

 {% endblock %}

</body>
</html>